version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: "mongodb+srv://<username>:<password>@cluster.mongodb.net/auth"
      JWT_SECRET: "your-secret-key"
      GOOGLE_CLIENT_ID: "your-google-client-id"
      GOOGLE_CLIENT_SECRET: "your-google-client-secret"
      FACEBOOK_APP_ID: "your-facebook-app-id"
      FACEBOOK_APP_SECRET: "your-facebook-app-secret"
      FRONTEND_URL: "http://localhost:3000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  product-service:
    build: ./product-service
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: "mongodb+srv://<username>:<password>@cluster.mongodb.net/products"
    volumes:
      - ./product-service:/app
      - /app/node_modules

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      PAYMOB_API_KEY: "your-paymob-key"
      AUTH_SERVICE_URL: "http://auth-service:3000"
    volumes:
      - ./order-service:/app
      - /app/node_modules