apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb+srv://test:test@lab10.5yizw4o.mongodb.net/auth
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: test
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: 826998097826-s7fo708eiq9bcdluq1s7h5fsnt5e4hfn.apps.googleusercontent.com
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: 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
        - name: FACEBOOK_APP_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: 031806359052103

        - name: FACEBOOK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: 6c2a0d854ee43e753dea9adceb7d8d3e
        - name: FRONTEND_URL
          value: "http://localhost:3000"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP