apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: order-uri
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:4000"
        - name: PAYMOB_API_KEY
          valueFrom:
            secretKeyRef:
              name: paymob-secret
              key: api-key
        - name: PAYMOB_INTEGRATION_ID
          valueFrom:
            secretKeyRef:
              name: paymob-secret
              key: integration-id
        - name: PAYMOB_IFRAME_ID
          valueFrom:
            secretKeyRef:
              name: paymob-secret
              key: iframe-id
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP