# filepath: /home/khaled/Documents/GitHub/E-Commerce_Backend/kubernetes/order-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb+srv://test:test@lab10.5yizw4o.mongodb.net/orders
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:4000"
        - name: PAYMENT_SERVICE_URL # Added
          value: "http://payment-service:3003" # Added
        # Removed PayMob keys as they are now in payment-service
        # - name: PAYMOB_API_KEY
        #   valueFrom: ...
        # - name: PAYMOB_INTEGRATION_ID
        #   valueFrom: ...
        # - name: PAYMOB_IFRAME_ID
        #   valueFrom: ...
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health # Assuming you have a /health endpoint in order-service
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe: # Added readiness probe
          httpGet:
            path: /health # Assuming you have a /health endpoint in order-service
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP