# filepath: /home/khaled/Documents/GitHub/E-Commerce_Backend/kubernetes/product-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb+srv://test:test@lab10.5yizw4o.mongodb.net/products
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3000"
        - name: REDIS_URL # Added
          value: "redis://redis:6379" # Added (points to the redis service)
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health # Assuming you have a /health endpoint in product-service
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe: # Added readiness probe
          httpGet:
            path: /health # Assuming you have a /health endpoint in product-service
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP